# Generated by Django 4.1.2 on 2022-10-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_visa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudio', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
            ],
        ),
    ]
